version: "3.8"

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_screener
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  sample_loader:
    image: python:3.11-slim
    depends_on:
      - db
    working_dir: /workspace
    volumes:
      - ./backend/database:/workspace
    command: ["/bin/bash", "-c", "pip install psycopg2-binary && python sample_loader.py"]

volumes:
  db_data: