name: Frontend CI Pipeline

on:
  push:
    branches: [ main, panchami ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Frontend build placeholder
        run: |
          echo "Running frontend build"