name: API Gateway CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: backend/api-gateway

    - name: Run tests
      run: npm test
      working-directory: backend/api-gateway

    - name: Build Docker image
      run: docker build -t api-gateway .
      working-directory: backend/api-gateway
